# Generated by Django 4.1.3 on 2023-01-02 19:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Blog', '0002_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
